
document.addEventListener("DOMContentLoaded", () => {
  const stops = [{"id": "delhi", "name": "Delhi", "x": 45, "y": 28, "region": "North", "fact": "Delhi has served as a major political and cultural centre across many periods of Indian history."}, {"id": "jaipur", "name": "Jaipur", "x": 35, "y": 38, "region": "West", "fact": "Jaipur is known as the Pink City and is famous for forts, palaces, and planned city design."}, {"id": "ahmedabad", "name": "Ahmedabad", "x": 29, "y": 50, "region": "West", "fact": "Ahmedabad is a UNESCO World Heritage City known for architecture, textiles, and the Sabarmati riverfront."}, {"id": "mumbai", "name": "Mumbai", "x": 31, "y": 66, "region": "West", "fact": "Mumbai is India's financial capital and a major coastal gateway on the Arabian Sea."}, {"id": "panaji", "name": "Panaji", "x": 34, "y": 76, "region": "West Coast", "fact": "Panaji is Goa's capital and reflects coastal, riverfront, and Indo-Portuguese heritage."}, {"id": "bengaluru", "name": "Bengaluru", "x": 45, "y": 78, "region": "South", "fact": "Bengaluru is a major technology hub located on the Deccan Plateau."}, {"id": "chennai", "name": "Chennai", "x": 55, "y": 80, "region": "South East", "fact": "Chennai is a historic port city on the Coromandel Coast."}, {"id": "kochi", "name": "Kochi", "x": 42, "y": 88, "region": "South West", "fact": "Kochi is known for backwaters, spice trade history, and coastal heritage."}, {"id": "hyderabad", "name": "Hyderabad", "x": 48, "y": 65, "region": "Deccan", "fact": "Hyderabad is known for Charminar, biryani, pearls, and Deccan history."}, {"id": "bhopal", "name": "Bhopal", "x": 47, "y": 49, "region": "Central", "fact": "Bhopal is called the City of Lakes and sits near important heritage and wildlife regions."}, {"id": "varanasi", "name": "Varanasi", "x": 63, "y": 43, "region": "North Central", "fact": "Varanasi is one of the world's oldest continuously inhabited cities and a major spiritual centre."}, {"id": "kolkata", "name": "Kolkata", "x": 78, "y": 49, "region": "East", "fact": "Kolkata is known for literature, art, colonial-era architecture, and the Hooghly River."}, {"id": "bhubaneswar", "name": "Bhubaneswar", "x": 70, "y": 61, "region": "East Coast", "fact": "Bhubaneswar is known as the Temple City of India."}, {"id": "guwahati", "name": "Guwahati", "x": 86, "y": 34, "region": "Northeast", "fact": "Guwahati is a gateway to Northeast India and sits on the Brahmaputra River."}, {"id": "gangtok", "name": "Gangtok", "x": 78, "y": 31, "region": "Himalayan East", "fact": "Gangtok is Sikkim's capital and is known for Himalayan views and Buddhist monasteries."}, {"id": "shimla", "name": "Shimla", "x": 42, "y": 21, "region": "Himalayan North", "fact": "Shimla is a hill station in Himachal Pradesh known for colonial-era architecture and mountain scenery."}];
  const puzzles = [{"level": "Easy", "start": "delhi", "target": "jaipur", "directions": ["southwest"], "clue": "From the national capital, move southwest to the Pink City.", "hint": "Rajasthan capital famous for Hawa Mahal."}, {"level": "Easy", "start": "mumbai", "target": "panaji", "directions": ["south"], "clue": "From India's financial capital, follow the west coast south to Goa's capital.", "hint": "A coastal capital on the Mandovi River."}, {"level": "Easy", "start": "bengaluru", "target": "chennai", "directions": ["east"], "clue": "From the tech hub, travel east toward the Coromandel Coast.", "hint": "Major Tamil Nadu port city."}, {"level": "Medium", "start": "jaipur", "target": "mumbai", "directions": ["southwest", "south"], "clue": "From the Pink City, go southwest, then continue south to a major Arabian Sea metropolis.", "hint": "The destination is Maharashtra's capital."}, {"level": "Medium", "start": "bhopal", "target": "kolkata", "directions": ["east", "east"], "clue": "From the City of Lakes, keep heading east across the plains until you reach the Hooghly region.", "hint": "A major cultural capital of eastern India."}, {"level": "Medium", "start": "hyderabad", "target": "kochi", "directions": ["southwest", "south"], "clue": "From the Deccan, travel southwest and then south toward Kerala's historic port.", "hint": "Famous for spice trade and backwaters."}, {"level": "Hard", "start": "shimla", "target": "chennai", "directions": ["southeast", "southeast", "south"], "clue": "From a Himalayan hill station, descend southeast twice, then turn south to the Coromandel Coast.", "hint": "The destination is a major coastal city in Tamil Nadu."}, {"level": "Hard", "start": "guwahati", "target": "ahmedabad", "directions": ["west", "southwest", "west"], "clue": "From the Brahmaputra gateway, cross westward, bend southwest through central India, and continue west to Gujarat.", "hint": "UNESCO World Heritage City on the Sabarmati."}, {"level": "Hard", "start": "gangtok", "target": "kochi", "directions": ["southwest", "southwest", "south"], "clue": "From the eastern Himalayas, move southwest twice across India, then south to the Malabar Coast.", "hint": "Kerala port city linked with spice routes."}];
  const saveKey = "incredible-india-compass-challenge-state";
  const directionVectors = { north:{x:0,y:-1}, northeast:{x:1,y:-1}, east:{x:1,y:0}, southeast:{x:1,y:1}, south:{x:0,y:1}, southwest:{x:-1,y:1}, west:{x:-1,y:0}, northwest:{x:-1,y:-1} };
  let state = { score: 0, solved: 0, attempts: 0, facts: [] };
  let currentPuzzle = null, currentStop = null, routeHistory = [], targetVisible = false, difficulty = "All";
  const map = document.getElementById("india-map");
  const feedback = document.getElementById("feedback-card");
  const factLog = document.getElementById("fact-log");
  const escapeHtml = (value) => String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
  function loadState(){try{const saved=JSON.parse(localStorage.getItem(saveKey)||"null"); if(saved && Array.isArray(saved.facts)) state=saved;}catch{state={score:0,solved:0,attempts:0,facts:[]};}}
  function saveState(){localStorage.setItem(saveKey, JSON.stringify(state));}
  function getStop(id){return stops.find((stop)=>stop.id===id);}
  function availablePuzzles(){return difficulty==="All" ? puzzles : puzzles.filter((puzzle)=>puzzle.level===difficulty);}
  function pickPuzzle(){const list=availablePuzzles(); currentPuzzle=list[Math.floor(Math.random()*list.length)]; currentStop=getStop(currentPuzzle.start); routeHistory=[currentStop.id]; targetVisible=false; feedback.className="feedback-card"; feedback.innerHTML=""; document.getElementById("mission-hint").hidden=true; renderMission(); renderMap(); updateStats();}
  function renderMission(){const target=getStop(currentPuzzle.target); document.getElementById("level-label").textContent=currentPuzzle.level; document.getElementById("mission-title").textContent=`${currentStop.name} → Mystery destination`; document.getElementById("mission-clue").textContent=currentPuzzle.clue; document.getElementById("mission-hint").textContent=currentPuzzle.hint; document.getElementById("start-city").textContent=getStop(currentPuzzle.start).name; document.getElementById("move-count").textContent=Math.max(0, routeHistory.length-1); document.getElementById("needed-count").textContent=currentPuzzle.directions.length; document.getElementById("target-status").textContent=targetVisible ? target.name : "Hidden"; document.getElementById("map-status").textContent=`Current city: ${currentStop.name}`;}
  function updateStats(){const accuracy=state.attempts ? Math.round((state.solved/state.attempts)*100) : 0; document.getElementById("score-total").textContent=state.score; document.getElementById("solved-total").textContent=state.solved; document.getElementById("accuracy-total").textContent=`${accuracy}%`; const rank=state.solved>=8?"Master navigator":state.solved>=5?"Trail commander":state.solved>=2?"Map reader":"Compass beginner"; document.getElementById("rank-label").textContent=rank;}
  function lineBetween(a,b){const dx=b.x-a.x, dy=b.y-a.y; const length=Math.sqrt((dx*dx)+(dy*dy)); const angle=Math.atan2(dy,dx)*180/Math.PI; return `<span class="trail-line" style="left:${a.x}%; top:${a.y}%; width:${length}%; transform: rotate(${angle}deg);"></span>`;}
  function renderMap(){const target=getStop(currentPuzzle.target); const lines=[]; for(let i=1;i<routeHistory.length;i+=1) lines.push(lineBetween(getStop(routeHistory[i-1]), getStop(routeHistory[i]))); const pins=stops.map((stop)=>{const classes=["map-pin"]; if(stop.id===currentStop.id) classes.push("current"); if(stop.id===target.id) classes.push(targetVisible?"target":"hidden-target"); const label=stop.id===target.id && !targetVisible ? "?" : stop.name; return `<span class="${classes.join(" ")}" style="left:${stop.x}%; top:${stop.y}%;">${escapeHtml(label)}</span>`;}); map.innerHTML=[...lines,...pins].join(""); renderMission();}
  function distanceAfterDirection(fromStop,direction){const vector=directionVectors[direction]; return stops.filter((stop)=>stop.id!==fromStop.id).map((stop)=>({stop, score:Math.abs((stop.x-fromStop.x)-(vector.x*16))+Math.abs((stop.y-fromStop.y)-(vector.y*16))})).sort((a,b)=>a.score-b.score)[0].stop;}
  function move(direction){const stepIndex=routeHistory.length-1; const expected=currentPuzzle.directions[stepIndex]; if(!expected){showResult(); return;} if(direction!==expected){state.attempts+=1; state.score=Math.max(0,state.score-3); saveState(); feedback.className="feedback-card visible"; feedback.innerHTML=`<strong>Wrong direction.</strong><br>You chose ${escapeHtml(direction.toUpperCase())}. Try undo or start a new puzzle.`; updateStats(); return;} currentStop=distanceAfterDirection(currentStop,direction); routeHistory.push(currentStop.id); if(routeHistory.length-1>=currentPuzzle.directions.length){showResult();}else{feedback.className="feedback-card visible"; feedback.innerHTML=`<strong>Good move.</strong><br>You travelled ${escapeHtml(direction.toUpperCase())} to ${escapeHtml(currentStop.name)}.`;} renderMap();}
  function showResult(){const target=getStop(currentPuzzle.target); const success=currentStop.id===target.id; state.attempts+=1; if(success){const earned=currentPuzzle.level==="Hard"?30:currentPuzzle.level==="Medium"?20:12; state.score+=earned; state.solved+=1; targetVisible=true; const factEntry=`${target.name}: ${target.fact}`; if(!state.facts.includes(factEntry)) state.facts.unshift(factEntry); feedback.className="feedback-card visible"; feedback.innerHTML=`<strong>Mission complete! +${earned} points.</strong><br>You reached <strong>${escapeHtml(target.name)}</strong>.<br>${escapeHtml(target.fact)}`;} else {feedback.className="feedback-card visible"; feedback.innerHTML=`<strong>Close, but not the target.</strong><br>You reached ${escapeHtml(currentStop.name)}. The hidden destination was ${escapeHtml(target.name)}.`; targetVisible=true;} saveState(); renderMap(); renderFacts(); updateStats();}
  function renderFacts(){if(!state.facts.length){factLog.innerHTML=`<div class="fact-item">Solve a route to unlock your first geography fact.</div>`; return;} factLog.innerHTML=state.facts.slice(0,8).map((fact)=>{const [city,...rest]=fact.split(": "); return `<div class="fact-item"><strong>${escapeHtml(city)}:</strong> ${escapeHtml(rest.join(": "))}</div>`;}).join("");}
  function undoMove(){if(routeHistory.length<=1){feedback.className="feedback-card visible"; feedback.innerHTML="<strong>Nothing to undo.</strong><br>You are already at the starting city."; return;} routeHistory.pop(); currentStop=getStop(routeHistory[routeHistory.length-1]); feedback.className="feedback-card visible"; feedback.innerHTML=`<strong>Move undone.</strong><br>You are back at ${escapeHtml(currentStop.name)}.`; renderMap();}
  document.querySelectorAll("[data-direction]").forEach((button)=>button.addEventListener("click",()=>move(button.dataset.direction)));
  document.getElementById("difficulty-select").addEventListener("change",(event)=>{difficulty=event.target.value; pickPuzzle();});
  document.getElementById("hint-button").addEventListener("click",()=>{document.getElementById("mission-hint").hidden=false;});
  document.getElementById("new-puzzle").addEventListener("click",pickPuzzle);
  document.getElementById("undo-move").addEventListener("click",undoMove);
  document.getElementById("reveal-target").addEventListener("click",()=>{targetVisible=true; renderMap();});
  document.getElementById("reset-progress").addEventListener("click",()=>{if(!confirm("Reset Indian Compass Challenge score and facts?")) return; state={score:0,solved:0,attempts:0,facts:[]}; saveState(); renderFacts(); updateStats(); feedback.className="feedback-card visible"; feedback.innerHTML="<strong>Score reset.</strong><br>Start navigating again!";});
  loadState(); renderFacts(); pickPuzzle();
  window.IndianCompassChallenge={stops:()=>[...stops], puzzles:()=>[...puzzles], newPuzzle:pickPuzzle};
});
